[package]
name = "devi"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = "4.4.18"
devimint = { workspace = true }
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
