
version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: swift
  directory: "/"
  schedule:
    interval: daily
