# THIS FILE IS AUTOGENERATED FROM FLAKEBOX CONFIGURATION
import "justfile.fedi"

alias b := build
alias c := check
alias t := test


[private]
default:
  @just --list


# run `cargo build` on everything
build:
  cargo build --all-targets


# run `cargo check` on everything
check:
  cargo check --all-targets


# run all checks recommended before opening a PR
final-check: lint clippy
  #!/usr/bin/env bash
  set -euo pipefail
  if [ ! -f Cargo.toml ]; then
    cd {{invocation_directory()}}
  fi
  just test-bridge


# run code formatters
format:
  #!/usr/bin/env bash
  set -euo pipefail
  if [ ! -f Cargo.toml ]; then
    cd {{invocation_directory()}}
  fi
  treefmt


# run lints
lint:
  #!/usr/bin/env bash
  set -euo pipefail
  export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME:-${TMPDIR:-/tmp}}/.cache}"
  flakebox-in-each-cargo-workspace cargo update --workspace --locked -q
  if command -v semgrep >/dev/null && [ -s .config/semgrep.yaml ]; then
    just semgrep
  fi
  while IFS= read -r path; do
    shellcheck --severity=warning "$path"
  done < <(git ls-files '*.sh')
  git diff --check HEAD
  treefmt -q --fail-on-change


# run tests
test: build
  #!/usr/bin/env bash
  set -euo pipefail
  if [ ! -f Cargo.toml ]; then
    cd {{invocation_directory()}}
  fi
  cargo test


# run and restart on changes
watch *ARGS="-x run":
  #!/usr/bin/env bash
  set -euo pipefail
  if [ ! -f Cargo.toml ]; then
    cd {{invocation_directory()}}
  fi
  env RUST_LOG=${RUST_LOG:-debug} cargo watch {{ARGS}}


# run cargo-crap on the workspace
crap *ARGS="--workspace":
  #!/usr/bin/env bash
  set -euo pipefail
  if [ ! -f Cargo.toml ]; then
    cd {{invocation_directory()}}
  fi
  cargo-crap {{ARGS}}


# run `cargo clippy` on everything
clippy *ARGS="--locked":
  cargo clippy --all-targets {{ARGS}}
  just clippy-wasm {{ARGS}}

[private]
clippy-wasm *ARGS:
  #!/usr/bin/env bash
  set -euo pipefail
  # Package names can collide with external dependencies; Cargo's exact
  # workspace package IDs keep every selected `--package` unambiguous.
  metadata=$(cargo metadata --locked --no-deps --format-version 1)
  workspace_packages=$(jq -r '.packages[].name' <<< "$metadata" | sort)
  wasm_dependencies=$(cargo tree --locked --target wasm32-unknown-unknown --package fedi-wasm --edges normal,build --prefix none | sed 's/ v[0-9].*//' | sort -u)
  wasm_packages=$(
    comm -12 \
      <(printf '%s\n' "$workspace_packages") \
      <(printf '%s\n' "$wasm_dependencies")
  )
  if [[ -z "$wasm_packages" ]]; then
    echo "fedi-wasm has no workspace dependencies to lint" >&2
    exit 1
  fi
  mapfile -t packages <<< "$wasm_packages"
  package_args=()
  for package in "${packages[@]}"; do
    mapfile -t package_ids < <(
      jq -r --arg package "$package" \
        '.packages[] | select(.name == $package) | .id' \
        <<< "$metadata"
    )
    if [[ ${#package_ids[@]} -eq 0 ]]; then
      echo "could not resolve workspace package ID for $package" >&2
      exit 1
    fi
    for package_id in "${package_ids[@]}"; do
      package_args+=(--package "$package_id")
    done
  done
  CLIPPY_CONF_DIR="$PWD/.config/clippy-wasm" cargo clippy "${package_args[@]}" --lib --no-deps --target wasm32-unknown-unknown {{ARGS}} -- --deny warnings --allow deprecated

# run `cargo clippy --fix` on everything
clippy-fix *ARGS="--locked":
  just clippy {{ARGS}} --fix


# run `semgrep`
semgrep:
  env SEMGREP_ENABLE_VERSION_CHECK=0 \
    semgrep --error --no-rewrite-rule-ids --config .config/semgrep.yaml


# check typos
[no-exit-message]
typos *PARAMS:
  #!/usr/bin/env bash
  set -eo pipefail

  export FLAKEBOX_GIT_LS
  FLAKEBOX_GIT_LS="$(git ls-files)"
  export FLAKEBOX_GIT_LS_TEXT
  FLAKEBOX_GIT_LS_TEXT="$(echo "$FLAKEBOX_GIT_LS" | grep -v -E "^db/|\.(png|ods|jpg|jpeg|woff2|keystore|wasm|ttf|jar|ico)\$")"


  if ! echo "$FLAKEBOX_GIT_LS_TEXT" | typos {{PARAMS}} --file-list - --force-exclude ; then
    >&2 echo "Typos found: Valid new words can be added to '.typos.toml'"
    return 1
  fi

# fix all typos
[no-exit-message]
typos-fix-all:
  just typos -w

# THIS FILE IS AUTOGENERATED FROM FLAKEBOX CONFIGURATION
