[package]
name = "stability-pool-client"
version = "0.3.0"
authors = ["The Stability Pool Developers"]
description = "stability pool module for fedimint"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
fedimint-client = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true }
strum_macros = { workspace = true }
bitcoin = { workspace = true, features = ["rand", "serde"] }
tracing = { workspace = true }
secp256k1-zkp = { workspace = true, features = ["serde", "bitcoin_hashes"] }
serde_json = { workspace = true }
erased-serde = { workspace = true }
stability-pool-common = { path = "../common" }
rand = { workspace = true }
async-stream = { workspace = true }
tokio = { workspace = true }
