[package]
name = "stability-pool-server"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
fedimint-server-core = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
erased-serde = { workspace = true }
stability-pool-common = { workspace = true }
itertools = { workspace = true }
tokio = { workspace = true }
