package com.fedi

import android.content.Context
import android.util.Log
import com.facebook.react.bridge.*
import com.facebook.react.modules.core.DeviceEventManagerModule.RCTDeviceEventEmitter
import org.fedi.fedi.*
import com.facebook.react.bridge.Arguments

import kotlinx.coroutines.*

object EventDispatcher : EventSink {
    override fun event(eventType: String, body: String) {
        BridgeNativeEventEmitter.send(eventType, body)
    }
}
class FedimintFfiModule(reactContext: ReactApplicationContext) :
        ReactContextBaseJavaModule(reactContext) {

    init {
        BridgeNativeEventEmitter.setContext(reactContext)
        // Must happen before any RPC: the bridge's DNS and interface lookups
        // read the Android Context through ndk-context, and panic without it.
        // The application context, not the react context, because it outlives
        // every activity.
        nativeInitAndroidContext(reactContext.applicationContext)
    }

    /**
     * Hands the Android Context to the Rust side.
     *
     * Declared here rather than generated by uniffi because uniffi has no way
     * to express a JNI object parameter. See
     * `bridge/fedi-ffi/src/android_context.rs` — the symbol is derived from
     * this class's package and name, so moving or renaming either breaks the
     * link at call time, not at build time.
     */
    private external fun nativeInitAndroidContext(context: Context)

    override fun getName(): String {
        return NAME
    }

    @ReactMethod
    fun initialize(options: String, promise: Promise) {
        GlobalScope.launch {
            val response = fedimintInitialize(EventDispatcher, options)
            promise.resolve(response)
        }
    }

    @ReactMethod
    fun rpc(method: String, payload: String, promise: Promise) {
        GlobalScope.launch {
            var response = fedimintRpc(method, payload)
            promise.resolve(response)
        }
    }

    @ReactMethod
    fun getSupportedEvents(promise: Promise) {
        var arrayList = fedimintGetSupportedEvents()
        var nativeArray = Arguments.fromList(arrayList);
        promise.resolve(nativeArray)
    }

    companion object {
        const val NAME = "FedimintFfi"

        init {
            // uniffi pulls the same library in through JNA, which does not
            // register its JNI methods with the JVM. Without this load,
            // `nativeInitAndroidContext` fails with UnsatisfiedLinkError.
            // Loading twice is a no-op — the OS returns the same handle.
            System.loadLibrary("fediffi")
        }
    }

}

object BridgeNativeEventEmitter {
    private var reactContext: ReactContext? = null

    fun setContext(reactContext: ReactContext) {
        this.reactContext = reactContext
    }

    fun send(eventType: String, body: Any) {
        if (this.reactContext === null) {
            return
        }

        this.reactContext!!.getJSModule(RCTDeviceEventEmitter::class.java).emit(eventType, body)
    }
}
