[package]
name = "fedi-social-common"
version = "0.3.0"
authors = ["The Fedimint Developers"]
edition = "2024"
description = "fedi-social is a Fedi's social backup&recovery module."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedi_social_common"
path = "src/lib.rs"

[dependencies]
fedimint-aead = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
bitcoin_hashes = { workspace = true }
hex = { workspace = true, features = ["serde"] }
fedimint-core = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
fedimint_threshold_crypto = { workspace = true }
impl-tools = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
