[package]
name = "stability-pool-client"
version = "0.3.0"
authors = ["The Stability Pool Developers"]
description = "stability pool module for fedimint"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
fedimint-client = { workspace = true }
fedimint-api-client = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
secp256k1 = { workspace = true }
serde_json = { workspace = true }
erased-serde = { workspace = true }
stability-pool-common = { workspace = true }
rand = { workspace = true }
async-stream = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
