pub const FEDI_STABILITY_POOL_MODULE_ENABLE_ENV: &str = "FEDI_STABILITY_POOL_MODULE_ENABLE";
pub const FEDI_STABILITY_POOL_MODULE_TEST_PARAMS_ENV: &str =
    "FEDI_STABILITY_POOL_MODULE_TEST_PARAMS";
pub const FEDI_SOCIAL_RECOVERY_MODULE_ENABLE_ENV: &str = "FEDI_SOCIAL_RECOVERY_MODULE_ENABLE";
