[package]
name = "stability-pool-server"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
bitcoin = { workspace = true }
tracing = { workspace = true }
secp256k1-zkp = { workspace = true }
reqwest = { workspace = true }
ring = { workspace = true }
serde_json = { workspace = true }
erased-serde = { workspace = true }
stability-pool-common = { path = "../common" }
rand = { workspace = true }
itertools = { workspace = true }
tokio = { workspace = true }
