name: Deploy to TestFlight (Fedi Nightly)
on:
    workflow_dispatch:
    workflow_call:

jobs:
    release-ios:
        name: Build iOS app and upload to TestFlight
        timeout-minutes: 90
        runs-on: [self-hosted, macos, arm64, legacy]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - uses: cachix/install-nix-action@v30
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v15
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
              continue-on-error: true

            - name: Build bridge
              run: nix develop .#xcode -c env BUILD_ALL_BRIDGE_TARGETS=1 CARGO_PROFILE=release scripts/ci/run-in-fs-dir-cache.sh build-bridge-ios ./scripts/bridge/build-bridge-ios.sh

            - name: Build UI dependencies
              run: nix develop -c ./scripts/ui/build-deps.sh

            - name: Install iOS dependencies (Cocoapods)
              # xcode shell ensures we have cocoapods installed
              run: nix develop .#xcode -c ./scripts/ui/install-ios-deps.sh

            - name: Inject secrets into .env file
              run: |
                  echo "CHANNEL_KEY_ANDROID=${{ secrets.ZENDESK_CHANNEL_KEY_ANDROID_DEV }}" >> ui/native/.env
                  echo "CHANNEL_KEY_IOS=${{ secrets.ZENDESK_CHANNEL_KEY_IOS_DEV }}" >> ui/native/.env
                  echo "ZENDESK_KID=${{ secrets.ZENDESK_KEY_ID_DEV }}" >> ui/native/.env
                  echo "ZENDESK_SECRET_KEY=${{ secrets.ZENDESK_SECRET_DEV }}" >> ui/native/.env
                  echo "FEDI_ENV=nightly" >> ui/native/.env

            - name: Generate JSON credentials file
              env:
                  ASC_API_KEY_JSON_CREDENTIALS_ENCODED: ${{ secrets.ASC_API_KEY_JSON_CREDENTIALS_ENCODED }}
              run: nix develop -c ./scripts/ci/make-testflight-creds.sh

            - name: Execute fastlane beta lane for CI
              env:
                  GH_PAT_FEDI_FETCH_IOS_CERTS: ${{ secrets.GH_PAT_FEDI_FETCH_IOS_CERTS }}
                  GH_PAT_FEDI_WRITE_IOS_CERTS: ${{ secrets.GH_PAT_FEDI_WRITE_IOS_CERTS }}
                  MATCH_KEYCHAIN_NAME: ${{ secrets.APP_STORE_CONNECT_KEYCHAIN_NAME }}
                  MATCH_PASSWORD: ${{ secrets.APP_STORE_CONNECT_KEYCHAIN_PASSWORD }}
                  BUILD_BRIDGE: 0
                  BUILD_UI_DEPS: 0
                  REINSTALL_PODS: 0
                  FLAVOR: 'nightly'
              run: |
                  ./scripts/ui/deploy-to-testflight.sh

            - name: Cleanup archives
              run: |
                  # this accumulates data for no good reason
                  rm -Rf $HOME/Library/Developer/Xcode/Archives
