name: Deploy to TestFlight
on:
    workflow_dispatch:
    pull_request:
        types:
            - closed
        branches:
            - 'master'

jobs:
    release-ios:
        if: >
            (github.event_name == 'workflow_dispatch') ||
            (
              github.event.pull_request.merged == true &&
              startsWith(github.head_ref, 'release/')
            )
        name: Build iOS app and upload to TestFlight
        runs-on: [self-hosted, macos, arm64]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - uses: cachix/install-nix-action@v26
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v14
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
              continue-on-error: true

            - name: Build bridge
              run: nix develop -c env BUILD_ALL_BRIDGE_TARGETS=1 CARGO_PROFILE=release scripts/ci/run-in-fs-dir-cache.sh build-bridge-ios ./scripts/bridge/build-bridge-ios.sh

            - name: Build UI dependencies
              run: nix develop -c ./scripts/ui/build-deps.sh

            - name: Install iOS dependencies (Cocoapods)
              # xcode shell ensures we have cocoapods installed
              run: nix develop .#xcode -c ./scripts/ui/install-ios-deps.sh

            - name: Generate JSON credentials file
              env:
                  ASC_API_KEY_JSON_CREDENTIALS_ENCODED: ${{ secrets.ASC_API_KEY_JSON_CREDENTIALS_ENCODED }}
              run: nix develop -c ./scripts/ci/make-testflight-creds.sh

            - name: Execute fastlane beta lane for CI
              env:
                  GH_PAT_FEDI_FETCH_IOS_CERTS: ${{ secrets.GH_PAT_FEDI_FETCH_IOS_CERTS }}
                  # TODO: for prod, regenerate certificates and convert these to secrets
                  MATCH_KEYCHAIN_NAME: 'ci-deploy.keychain'
                  MATCH_KEYCHAIN_PASSWORD: 'fedibtc'
                  MATCH_PASSWORD: 'fedibtc'
                  # Consider: should we even have separate steps above for this?
                  BUILD_BRIDGE: 0
                  BUILD_UI_DEPS: 0
                  REINSTALL_PODS: 0
              run: |
                  ./scripts/ui/deploy-to-testflight.sh
