name: Test CI Workflow
on:
    workflow_dispatch:

# This workflow is used as a generic way to test arbitrary workflows on CI runners
# The version of this workflow on master should always be a no-op with a placeholder step
# developers can branch off and add steps or scripts and then manually dispatch this workflow
# from their branch to test what the CI run would look like
jobs:
    test-ci-workflow:
        name: Test CI Workflow
        timeout-minutes: 90
        runs-on: [self-hosted, macos, arm64]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - uses: cachix/install-nix-action@v30
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v15
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
              continue-on-error: true

            - name: Test script
              run: |
                  echo "Add your scripts here"
