name: Vercel Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches-ignore:
            - master
            - vercel/production
        paths:
            - .github/workflows/vercel-preview.yml
            - scripts/ci/vercel-preview.sh
            - ui/web/**
            - ui/common/**
jobs:
    Deploy-Preview:
        runs-on: [self-hosted, linux]
        environment:
            name: Preview
            url: ${{steps.deploy.outputs.url}}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - uses: cachix/install-nix-action@V27
              with:
                  nix_path: nixpkgs=channel:nixos-23.05

            - uses: cachix/cachix-action@v14
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build & Deploy with Vercel (Preview)
              id: deploy
              run: nix develop .#vercel -c env VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} ./scripts/ci/vercel-preview.sh
