name: Vercel Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - master
            - vercel/production
        paths:
            - .github/workflows/vercel-prod.yml
            - scripts/ci/vercel-prod.sh
            - scripts/build-wasm.sh
            - scripts/ui/install-wasm.sh
            - bridge/fedi-wasm/**
            - ui/web/**
            - ui/common/**
jobs:
    Deploy-Production:
        runs-on: [self-hosted, linux, legacy]
        environment:
            name: Production
            url: ${{steps.deploy.outputs.url}}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - uses: cachix/install-nix-action@v30
              with:
                  nix_path: nixpkgs=channel:nixos-23.05

            - uses: cachix/cachix-action@v15
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build & Deploy with Vercel (Production)
              id: deploy
              run: nix develop .#vercel -c env VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} ./scripts/ci/vercel-prod.sh
